export default function Post() {
  return (
    <>
      <p>Most homeowners searching for a garage conversion contractor assume any licensed general contractor can handle the job. That assumption is wrong in ways that can derail your permit, void your insurance, and leave structural or electrical work incomplete with no legal recourse. The license classification your contractor holds determines what they are legally permitted to touch &mdash; and on a garage conversion, the scope is wider than most people expect.</p>
      <p>A garage-to-living-space conversion triggers structural, electrical, plumbing, mechanical, and fire separation requirements simultaneously. Whether your contractor needs a Class B general building license, whether they need specialty trade licenses for the electrical and plumbing work, and which permit track you are on (straight conversion vs. ADU) all depend on specifics you need to understand before you sign anything.</p>

      <h2>What type of contractor license is required for a garage conversion?</h2>
      <p>A Class B general building contractor license (or your state&apos;s equivalent) covers structural work on a garage conversion. In California, a B-2 Residential Remodeler license does not authorize load-bearing wall work or electrical and plumbing connections &mdash; those require separate specialty licenses or a full Class B. The license scope must match the full scope of work.</p>
      <p>California&apos;s B-2 license was introduced in 2021 and carved out specifically to cover cosmetic residential remodeling. It explicitly excludes work on load-bearing elements, electrical service panels, and plumbing drain, waste, and vent systems. A garage conversion almost always touches at least one of those three categories.</p>
      <p>Other states use different license classifications but apply the same logic: the contractor&apos;s license must cover every category of work they perform on your project. California&apos;s CSLB lists over 280,000 active licensees, but the classification on that license is what matters &mdash; not just that the number is active.</p>
      <p><a href="/blog/licensed-vs-bonded-vs-insured-contractors">Verify the exact license classification before signing a contract</a>, not after you&apos;ve already scheduled a start date.</p>

      <h2>Do electricians and plumbers working on a garage conversion need their own licenses?</h2>
      <p>Yes. Electrical and plumbing work on a garage conversion must be performed by licensed trade contractors, either as separate hires or as licensed subcontractors under your general contractor. A GC cannot legally self-perform electrical or plumbing work in most states without holding the applicable trade license. Your GC manages the project and holds structural scope; the trade licenses are separate.</p>
      <p>Most garage conversions require new electrical circuits, a possible subpanel, HVAC, and plumbing if a bathroom is included. Each of those trades carries its own independent state license. The GC&apos;s Class B license does not extend to those trades.</p>
      <p>Homeowners can independently verify each subcontractor&apos;s license &mdash; don&apos;t take the GC&apos;s word for it. According to the FTC, home improvement fraud costs consumers over $3 billion annually, and subcontractor license fraud is a documented subset of that figure. You can run each subcontractor&apos;s name or license number through <a href="https://checklicensed.com">CheckLicensed.com</a> to confirm their trade license is active before any work begins.</p>
      <p><a href="/blog/do-subcontractors-need-license">Check each subcontractor&apos;s license before work begins</a>, not after the drywall is up.</p>

      <h2>What structural requirements does an attached garage conversion trigger?</h2>
      <p>An attached garage conversion must meet IRC R302.6, which requires a fire-rated wall assembly between the garage space and the living area. At minimum this means 1/2-inch Type X gypsum board on the garage side, a 20-minute fire-rated door with a self-closing mechanism, and no penetrations that compromise the assembly. Local amendments often increase these requirements.</p>
      <p>Some California jurisdictions require 5/8-inch Type X gypsum board rather than the IRC baseline. The fire separation requirement applies even when the garage slab becomes the habitable floor area &mdash; the boundary with any remaining garage or mechanical space still needs a compliant fire-rated assembly.</p>
      <p>The shared wall between a house and an attached garage is almost always load-bearing. Any modification to that wall requires engineering sign-off and falls under Class B license scope, not B-2. This is one of the clearest reasons why a B-2 license is insufficient for most attached garage conversions.</p>
      <p>Detached garage conversions don&apos;t trigger IRC R302.6, but they still require compliance with insulation minimums, egress window requirements, and electrical standards for habitable space. The license scope question applies either way.</p>

      <h2>What is the difference between a garage conversion permit and an ADU permit?</h2>
      <p>A straight garage conversion &mdash; turning the space into a home office, gym, or extra bedroom connected to the main house &mdash; goes through a residential alteration permit. An ADU garage conversion, which creates a separate dwelling unit with its own kitchen and address, goes through an ADU permit track with different review timelines, impact fees, and setback rules.</p>
      <p>A non-ADU alteration permit typically takes 30 to 60 days for approval. There are no impact fees, and separate utility metering is not required. The project stays under your existing address and is treated as an addition to the main dwelling.</p>
      <p>An ADU permit typically takes 60 or more days. It triggers school impact fees and utility connection fees in many California cities, requires a separate address, and is subject to its own zoning review. The permit type determines which inspections are required and what license number appears on the permit application.</p>
      <p>Before you choose a contractor, decide which permit track you are on. That decision affects the license requirements, the timeline, and the fees. <a href="/blog/adu-contractor-license-requirements">How the ADU permit process differs from a standard alteration permit</a> is covered separately &mdash; the license tables for ADU work are not duplicated here.</p>

      <h2>How do I verify a garage conversion contractor&apos;s license before signing?</h2>
      <p>Pull the contractor&apos;s license number from their bid or business card and check it directly through your state licensing board&apos;s database. Confirm the license classification covers the full scope of your project, verify the license is active and not expired or suspended, and check whether any complaints or disciplinary actions are on record.</p>
      <p>Verify before signing a contract, not after the permit is submitted. Disciplinary history on structural work &mdash; a complaint about substandard framing or unpermitted work on a prior project &mdash; is a proxy for structural quality risk on your project. The same state database that shows license status also shows expiration date, bond amount, and workers&apos; comp certificate.</p>
      <p>CheckLicensed.com pulls the license record, current status, classification, and any complaint history in one lookup &mdash; faster than navigating each state board&apos;s database directly. Run the check before your first contractor meeting, not after you&apos;ve agreed on a price.</p>
      <p><a href="/blog/contractor-workers-comp-insurance-what-it-means">Confirm workers&apos; comp coverage is active</a> in the same verification step. An unlicensed or uninsured worker injured on your property can result in personal liability.</p>

      <h2>What happens if the garage conversion contractor isn&apos;t licensed for the full scope of work?</h2>
      <p>If the contractor&apos;s license doesn&apos;t cover the scope of work they perform, the permit can be flagged, inspections can fail, and the work may need to be demolished and redone by a properly licensed contractor. You also lose most legal remedies &mdash; courts frequently void contractor claims when work was performed outside the license scope.</p>
      <p>In California, a contractor performing work outside their license classification can be reported to the CSLB and faces license suspension. The contractor&apos;s general liability policy may also deny claims for damage if the work was outside the license scope, leaving you with no insurance backstop from their policy.</p>
      <p>The homeowner bears the correction cost in most cases. Out-of-scope work is not covered by the state contractor recovery fund if the homeowner knew the contractor was operating outside their license classification. That &quot;knew or should have known&quot; standard is applied broadly.</p>
      <p>The practical step is simple: request the license number, classification, and expiration date before the first meeting. Legitimate contractors provide this immediately without hesitation.</p>
    </>
  );
}
