export default function Post() {
  return (
    <>
      <p>Hiring a contractor for your primary home is a financial risk. Hiring an unlicensed or underinsured contractor for a rental property is a legal liability that can follow you through tenant lawsuits, insurance claim denials, and city-ordered building inspections. The stakes are categorically different, and most landlords do not find out how different until something goes wrong.</p>
      <p>The implied warranty of habitability, standard landlord insurance exclusions for unlicensed work, and the multi-unit multiplication effect all mean that the contractor verification steps that are optional-but-smart for homeowners are effectively mandatory for landlords. This post explains exactly what to verify, why, and in what order.</p>

      <h2>Are landlords legally required to use licensed contractors?</h2>
      <p>Yes. In most states, any contractor performing work over the licensing threshold &mdash; often $500 to $1,000 in combined labor and materials &mdash; must hold a state license. Landlords are subject to the same licensing requirements as homeowners. But landlords face an additional legal layer: the implied warranty of habitability creates strict liability when defective contractor work produces unsafe living conditions.</p>
      <p>Strict liability means a tenant does not need to prove the landlord was negligent. If defective contractor work creates a habitability violation, the landlord is liable even without prior knowledge of the defect. That is a meaningful legal distinction from homeowner exposure: a homeowner bears the personal financial cost but has no strict liability to a third party.</p>
      <p>Licensing follows the work, not the property type. Whether your rental is a single-family home or a 12-unit building, the state threshold applies. <a href="/blog/what-happens-hire-unlicensed-contractor">What it means to hire an unlicensed contractor</a> covers the homeowner-facing penalties in detail &mdash; add strict tenant liability on top of every consequence listed there.</p>

      <h2>Does landlord insurance cover damage from unlicensed contractor work?</h2>
      <p>Typically no. Standard landlord insurance policies exclude damage caused by unlicensed contractors. If an unlicensed electrician&apos;s faulty wiring causes a fire or a plumber without a license triggers a flood, the landlord insurance carrier can deny the claim on the basis that the work was performed by an unlicensed party. The landlord absorbs the full cost.</p>
      <p>This exclusion is not prominently disclosed. Most landlords discover it during a claim denial, not when reviewing their policy. Ask your carrier explicitly &mdash; before hiring any contractor &mdash; whether your policy excludes claims from unlicensed contractor work.</p>
      <p>According to the FTC, home improvement fraud costs consumers over $3 billion annually. Landlords are concentrated high-value targets because they manage multiple properties and often aren&apos;t on-site when work is performed. For a primary homeowner, an unlicensed contractor failure produces a personal financial loss. For a landlord, a denied insurance claim combines with tenant liability to produce a compounding loss.</p>
      <p><a href="/blog/what-is-general-liability-insurance-contractor">What general liability insurance actually covers on a job site</a> explains the distinction between contractor GL coverage and your landlord policy &mdash; the two are separate, and both matter.</p>

      <h2>What is the difference between a certificate of insurance and an additional insured endorsement?</h2>
      <p>A certificate of insurance (COI) proves a contractor had insurance at a point in time. An additional insured endorsement on the contractor&apos;s general liability policy means you as the landlord are covered by that policy for claims arising from the contractor&apos;s work. A COI alone does not give you any coverage &mdash; the endorsement does.</p>
      <p>Most landlords request a COI. Very few request to be added as an additional insured. The COI is the minimum; the endorsement is the actual protection. The endorsement takes one business day and costs the contractor nothing &mdash; it is issued directly by the contractor&apos;s insurance broker.</p>
      <p>If a tenant is injured by a contractor&apos;s work, a COI only proves the contractor had insurance at the time. An additional insured endorsement means the contractor&apos;s GL policy responds to claims that name you as the landlord. Ask the contractor&apos;s broker to issue a certificate naming you as additional insured on the GL policy before work begins.</p>
      <p><a href="/blog/contractor-workers-comp-insurance-what-it-means">What a contractor&apos;s workers&apos; comp policy covers vs. what it doesn&apos;t</a> is a separate question from GL &mdash; both matter on a rental property. And <a href="/blog/licensed-vs-bonded-vs-insured-contractors">verify the contractor is licensed, bonded, and insured</a> before the first crew member sets foot on the property.</p>

      <h2>Who is liable if a contractor injures a tenant on a rental property?</h2>
      <p>Both the contractor and the landlord can be named in a tenant injury claim. If the contractor is licensed, insured, and you are named as additional insured on their GL policy, the contractor&apos;s policy responds first. If the contractor is unlicensed or uninsured, the landlord faces direct liability with no insurance backstop. Tenant injury during contractor work is one of the highest-exposure scenarios in residential real estate.</p>
      <p>Landlord exposure is reduced but not eliminated even with a fully licensed and insured contractor. A court will ask whether the landlord took reasonable steps to hire qualified workers. License verification before hiring is documented due diligence &mdash; it strengthens your legal position if a claim is filed.</p>
      <p>CheckLicensed.com provides a timestamped license lookup record. If a tenant later claims the contractor was unqualified, you have documented evidence of the verification you ran before hiring. That record can matter in litigation.</p>
      <p><a href="/blog/homeowner-liability-unlicensed-contractor-injury">How landlord liability works when an unlicensed contractor gets hurt on the property</a> covers the workers&apos; comp angle separately &mdash; an uninsured contractor injury on your property can also produce personal liability.</p>

      <h2>How does contractor risk multiply on multi-unit rental properties?</h2>
      <p>In a single-family rental, defective electrical or plumbing work affects one unit. In a multi-unit building, the same work often runs through shared systems that affect every unit simultaneously &mdash; and a single habitability violation can trigger a city inspection of the entire building, not just the unit where the work occurred.</p>
      <p>Multi-unit properties share electrical panels, plumbing stacks, HVAC systems, and structural elements. Defective work on one unit may violate habitability for every unit on the same circuit or plumbing stack. A tenant complaint in one unit can produce notices of violation across the whole building.</p>
      <p>A phased renovation of an occupied building may not be covered by a standard landlord policy. You may need an explicit occupied-building coverage endorsement or a separate builder&apos;s risk policy during active renovation. Check with your carrier before work starts, not after a claim is denied.</p>
      <p>The cost equation is simple: a pre-hire license check costs nothing. A single tenant lawsuit over habitability from unlicensed contractor work routinely costs $10,000 to $50,000 or more in legal fees, before any settlement.</p>

      <h2>What tenant notice requirements apply when hiring a contractor for an occupied rental?</h2>
      <p>Most states require landlords to give tenants 24 hours&apos; notice before a contractor enters for inspections and 1 to 7 days&apos; written notice before a contractor enters for planned repairs or renovation. Entering without proper notice can constitute a breach of the lease and, in some states, a statutory violation with per-day penalties.</p>
      <p>The 24-hour rule is common for inspections and emergency repairs. Written notice of 24 hours to 7 days is typical for planned non-emergency work, with the exact window varying by state. Check your state&apos;s landlord-tenant statute before scheduling any contractor visit.</p>
      <p>The contractor is an agent of the landlord for entry notice purposes. If a contractor enters without proper notice, the landlord bears the liability &mdash; not the contractor. The practical process: give written notice (email is acceptable in most states), document the date and time, and keep a record of the contractor&apos;s work schedule. <a href="/blog/homeowner-rights-during-renovation">Tenants&apos; rights during a renovation</a> covers what tenants can and cannot legally require during active work.</p>

      <h2>What should I verify before hiring a contractor for a rental property?</h2>
      <p>Before hiring any contractor for a rental property, verify: active license status and the correct classification for your project scope, general liability insurance with you named as additional insured, workers&apos; compensation coverage, current bond amount, and any disciplinary history. Collect all of these in writing before signing a contract.</p>
      <p>License verification covers active status, correct classification, and no suspensions or pending disciplinary actions. A lapsed bond means no surety recovery if the contractor abandons the job. Complaints about abandoned projects, unpaid subcontractors, or substandard work are visible on most state licensing databases and matter more on a rental property than on an owner-occupied home.</p>
      <p>CheckLicensed.com consolidates license status, classification, expiration, bond, and complaint history in one lookup. For a rental property, run this check on every contractor and every subcontractor before work starts. <a href="/blog/do-subcontractors-need-license">Subcontractors working on your rental also need independent licenses</a> &mdash; the GC&apos;s license does not extend to trade work performed by unlicensed subs.</p>
    </>
  );
}
