export default function Post() {
  return (
    <>
      <p>A worker falls off a ladder at your house. You assumed that was his problem &mdash; he&apos;s a contractor, not your employee. Then you get a letter from his attorney. Depending on one factor &mdash; whether he held a valid contractor&apos;s license &mdash; you may have just become his legal employer.</p>

      <p>This is the statutory employer doctrine, and most homeowners have never heard of it. It transforms the legal relationship between you and a contractor the moment the contractor is unlicensed. Here is exactly how it works, what states have adopted it, and how to make sure you are never on the wrong side of it.</p>

      <h2>Who is liable if a contractor gets hurt on my property?</h2>
      <p>It depends on whether the contractor is licensed. If licensed and carrying workers&apos; compensation insurance, the contractor&apos;s own policy covers their injury and you have no liability. If the contractor is unlicensed, several states treat you as the legal employer &mdash; which means you may be personally responsible for medical costs, lost wages, and more.</p>
      <p>Two distinct injury scenarios create different levels of exposure. The first is the contractor themselves getting hurt &mdash; a fall, a tool accident, an equipment failure. The second, and more dangerous scenario, is when one of the contractor&apos;s employees is injured on your site. Both can generate claims against you, but the employee scenario often involves higher stakes because you may not even know the worker exists.</p>
      <p>Construction is the most dangerous industry in the United States. According to OSHA, construction accounts for more than 20 percent of all private-sector fatal workplace injuries. Falls alone account for nearly half of construction fatalities &mdash; what OSHA calls the &quot;Fatal Four.&quot; The work happening at your home is statistically among the most injury-prone work that exists.</p>
      <p>Premises liability &mdash; the legal duty you owe to anyone on your property &mdash; is the lesser issue here. It applies to licensed and unlicensed contractors alike. The statutory employer doctrine is the real trap, and it only activates when the contractor is unlicensed. Learn about <a href="/blog/contractor-workers-comp-insurance-what-it-means">workers&apos; comp insurance your contractor carries</a> and why it matters before any project starts.</p>

      <h2>What is the statutory employer doctrine?</h2>
      <p>The statutory employer doctrine is a legal rule, adopted by multiple states, that reclassifies a property owner as the legal employer of any unlicensed contractor they hire. If the contractor doesn&apos;t hold a valid license, the law treats the hiring homeowner as if they put the worker on payroll &mdash; including full employer liability for workplace injuries.</p>
      <p>Workers&apos; compensation laws were designed so that injured workers always have a source of recovery. The system assumes that if a contractor is injured, their workers&apos; comp policy pays &mdash; no lawsuit needed. But when a contractor is unlicensed, that coverage chain breaks. States close the gap by making the property owner the fallback employer.</p>
      <p>California has the most explicit codification. California Labor Code &sect;2750.5 states that a person who hires an unlicensed contractor is deemed to be the employer of that contractor and any employees of that contractor. The result: full employer liability, as if you had hired the worker directly.</p>
      <p>The statutory employer principle extends to multiple states beyond California. The specific statute numbers vary and not every state has codified it in identical language, but the underlying policy logic &mdash; that unlicensed contracting transfers employer risk to the property owner &mdash; appears in workers&apos; comp frameworks across the country. If you are outside California, consult a construction attorney in your state before assuming you are not exposed.</p>

      <h2>Does homeowners insurance cover contractor injuries?</h2>
      <p>Maybe &mdash; but not if the contractor is unlicensed. Standard homeowners policies include personal liability coverage that can respond to certain injuries on your property. However, most policies explicitly exclude coverage for injuries caused by or involving unlicensed contractors. Hiring unlicensed work can void the claim before you ever file it.</p>
      <p>Standard homeowners policies carry a personal liability section, typically $100,000 to $300,000 in coverage, that responds to bodily injury claims arising on your property. On the surface, this seems like a safety net for contractor injuries. But read the exclusions. Most policies contain language that voids coverage when the contractor performing the work was not properly licensed.</p>
      <p>Medical payments coverage &mdash; sometimes called MedPay &mdash; is a separate, no-fault section of many homeowners policies. It typically covers $1,000 to $5,000 in medical expenses for injuries on your property, regardless of fault. That sounds helpful until you understand the math: a serious construction fall involving surgery, hospitalization, and lost wages can run $200,000 or more. MedPay does not come close.</p>
      <p>Unlicensed contractor work may also affect your ability to file property damage claims if something goes wrong during the project. The same exclusions that strip liability coverage can apply to damage done to your home. Call your insurer before any project begins and ask directly: &quot;Does my policy cover injuries or property damage if the contractor is unlicensed?&quot; Get the answer in writing. See also: <a href="/blog/insurance-claim-unlicensed-contractor">homeowners insurance and unlicensed contractor claims</a>.</p>

      <h2>Can a contractor sue me if they get injured on my property?</h2>
      <p>Yes. A contractor &mdash; licensed or not &mdash; can sue you for injuries sustained on your property. If they&apos;re unlicensed, your exposure is greater: you can be treated as their employer under the statutory employer doctrine, which means workers&apos; comp claims, tort claims, and potentially claims from their employees too.</p>
      <p>Premises liability is the starting point for any injury lawsuit on your property. As a homeowner, you owe a &quot;reasonable care&quot; duty to contractors as business invitees. If there was a hazard you knew about and didn&apos;t disclose &mdash; a rotted deck section, a poorly marked step, an electrical panel issue &mdash; you can face a negligence claim regardless of whether the contractor was licensed.</p>
      <p>The statutory employer doctrine opens a second, larger door. If the contractor is unlicensed, you are not just liable for hazardous conditions you created &mdash; you are potentially liable as their employer for the injury itself. Workers&apos; comp exposure in serious construction accidents can reach hundreds of thousands of dollars. And if the unlicensed contractor brought workers with them, those workers can also file claims against you under the same theory.</p>
      <p>&quot;I didn&apos;t know he was unlicensed&quot; is not a recognized defense in most states that apply the statutory employer doctrine. The rule places the burden of verification on the property owner, not on the worker. Just as <a href="/blog/can-i-sue-unlicensed-contractor">you have legal options when a contractor wrongs you</a>, the contractor can come after you when they are hurt &mdash; and an unlicensed status amplifies your exposure significantly.</p>

      <h2>What is the difference between a licensed contractor&apos;s injury and an unlicensed one?</h2>
      <p>A licensed contractor carrying workers&apos; compensation insurance is generally a closed system: if they&apos;re hurt, their workers&apos; comp policy pays. You stay out of it. An unlicensed contractor has no such system &mdash; and the law fills that gap by handing the employer role to you.</p>
      <p>Think of the workers&apos; comp chain. A licensed contractor is required to carry workers&apos; comp coverage. If a worker is injured, the workers&apos; comp insurer pays for medical treatment, a portion of lost wages, and rehabilitation. The homeowner is not a party to that transaction. You never see the bill.</p>
      <p>Break the chain at step one &mdash; no valid license &mdash; and the statutory employer doctrine activates. There is no insurer to absorb the loss. The law assigns that role to you. The injured worker (or their attorney) then has a clear path to your homeowners policy, your personal assets, or both.</p>
      <p>One important nuance: even a licensed contractor can have a lapsed or inadequate workers&apos; comp policy. A lapsed policy creates real problems for the contractor and for you, but it is legally different from the unlicensed contractor scenario. In the licensed-but-lapsed situation, you are not reclassified as the employer under the statutory doctrine &mdash; the contractor is still the employer, just an underinsured one. Sole proprietors in some states can legally opt out of workers&apos; comp coverage for themselves &mdash; but they still need a valid license for the rest of the analysis to apply.</p>

      <h2>Am I responsible for workers&apos; comp if I hire a contractor?</h2>
      <p>Not if the contractor is properly licensed and carries their own workers&apos; comp policy. But if they&apos;re unlicensed &mdash; or if they have employees who aren&apos;t covered &mdash; you may be. Ask every contractor for a certificate of insurance showing active workers&apos; comp coverage before work begins. Don&apos;t accept verbal assurances.</p>
      <p>A certificate of insurance (COI) is a one-page document issued by the contractor&apos;s insurer that summarizes their active coverage. It lists the policy type, coverage limits, and policy period. When you receive one, look at the expiration date first. A COI that expired three months ago is not coverage &mdash; it is proof that coverage once existed.</p>
      <p>After confirming the date, call the insurer directly and verify the policy is still active. Insurers will confirm active coverage without disclosing policy details. This takes two minutes and is the only way to know the COI is not fabricated or outdated.</p>
      <p>If you are hiring a general contractor who will bring subcontractors to your property, the analysis extends to those subs. A licensed GC does not insulate you from liability if the sub is unlicensed and one of the sub&apos;s workers is hurt at your home. Verify the license status of the GC and ask specifically whether their subs are licensed and covered.</p>

      <h2>How do I verify a contractor&apos;s license before work starts?</h2>
      <p>Search the contractor&apos;s license through your state&apos;s licensing board database before signing anything. Verify the license is active, check that the classification covers the work being done, and review any disciplinary history. An active license in the wrong classification can still leave you exposed.</p>
      <p>The process is straightforward. Go to your state&apos;s contractor licensing board website &mdash; most have a license lookup tool where you can search by contractor name or license number. Confirm the status reads &quot;Active,&quot; not &quot;Expired,&quot; &quot;Suspended,&quot; or &quot;Revoked.&quot; A suspended or revoked license is worse than no license at all because it signals prior disciplinary problems.</p>
      <p>Check the classification. A license in the correct state but the wrong classification is insufficient. A plumber&apos;s license does not cover electrical work. A general building license may not cover specialty trades. If the classification does not match the job, you have the same exposure as if they were unlicensed.</p>
      <p>Disciplinary history matters too. Prior workers&apos; comp violations, safety citations, or complaints about unlicensed workers on job sites are patterns worth knowing. <a href="https://checklicensed.com">CheckLicensed.com</a> pulls license status, classification, and disciplinary history in one place &mdash; it&apos;s the fastest way to run this check before you hire. You can also cross-reference <a href="/blog/licensed-vs-bonded-vs-insured-contractors">what licensed, bonded, and insured actually means</a> and review the <a href="/blog/what-happens-hire-unlicensed-contractor">full consequences of hiring unlicensed</a> before making any hiring decision.</p>

      <h2>What should I do if a worker is already injured at my home?</h2>
      <p>Call 911 if there is a medical emergency. Then call your homeowners insurance company immediately &mdash; before speaking to any attorney representing the worker. Document everything: photos of the scene, the contractor&apos;s license information (or absence of it), and any witnesses. Do not admit fault and do not make payments directly to the injured worker.</p>
      <p>Medical care comes first. Once the scene is safe and help is on the way, begin building your documentation. Photograph the area where the injury occurred, the equipment involved, and any conditions that may have contributed. Write down what you know about the contractor: name, company, license number if they gave you one, insurance certificate if they provided it.</p>
      <p>Call your homeowners insurer the same day, even if you are not sure you have a claim. Late reporting can affect your coverage or give the insurer a basis to deny the claim later. Your insurer&apos;s claims team will guide next steps and may assign a defense attorney if a lawsuit is filed.</p>
      <p>Do not make direct payments to the injured worker, even as a gesture of goodwill. Direct payments can be construed as an admission of employer status or fault, which complicates your legal position significantly. If the contractor was unlicensed, consult a construction attorney in your state before making any statements or payments.</p>

      <p>The legal exposure from a contractor injury on your property scales directly with whether that contractor held a valid license. A licensed, insured contractor means their system handles it. An unlicensed one means you may be the system. The single most effective protection is verification before the first nail is driven.</p>
    </>
  );
}
