export default function Post() {
  return (
    <>
      <p>Siding is one of the top targets for storm-chaser fraud. After any hail event or hurricane season, contractors who didn&apos;t exist last week are suddenly knocking on doors with clipboards, quoting jobs, collecting deposits, and disappearing. The most reliable filter against them is a license check &mdash; but siding licensing is messier than most trades because the rules change significantly by state.</p>

      <p>Some states require a siding-specific specialty license. Others accept a general contractor license with the right classification. A handful have no state-level requirement at all &mdash; but may have local or county rules. Here is how to figure out exactly what applies in your state, what to look for, and what to do if a contractor can&apos;t produce proof.</p>

      <h2>Do siding contractors need to be licensed?</h2>
      <p>In most states, yes &mdash; but the type of license required varies. Some states issue a dedicated siding specialty license. Others require a general contractor&apos;s license with a specific classification that covers exterior work. A few states have no state-level siding license requirement but leave it to local jurisdictions. The contractor&apos;s license type matters as much as whether they have one.</p>
      <p>The important distinction is that having any contractor license is not sufficient. The classification within the license must actually cover siding or exterior construction. A licensed electrician cannot install your siding &mdash; obviously. But a licensed general contractor whose classification covers only structural work may also be ineligible to perform siding installation legally in your state.</p>
      <p>Permits are a separate issue from licensing and follow local jurisdiction rules. A contractor can be fully licensed and still fail to pull the required permit for a re-siding project, which creates problems for you down the line. Both checks matter, but they are different checks.</p>

      <h2>What type of license does a siding contractor need?</h2>
      <p>It depends on the state. California requires either a D-41 (Siding and Decking) specialty license or a C-61 classification from the CSLB. Nevada requires a C-15 (Roofing and Siding) license. In Florida as of 2025, local contractor licenses were phased out &mdash; contractors must now hold a state license through the DBPR. In states without a siding-specific classification, a general building contractor license with exterior work coverage typically applies.</p>
      <p>In California, the Contractors State License Board (CSLB) issues a D-41 classification specifically for Siding and Decking work. A contractor may also hold a broader C-61 limited specialty license that includes exterior work. If you are in California, verify the specific classification &mdash; not just that the contractor holds a CSLB license. Any CSLB license without the right classification does not make them legally authorized for your project.</p>
      <p>Nevada&apos;s C-15 classification covers both Roofing and Siding under the Nevada State Contractors Board (NSCB). Florida simplified its system significantly: as of June 30, 2025, local and county contractor licenses were phased out statewide. Contractors in Florida must now hold a state-issued license through the Department of Business and Professional Regulation (DBPR). A local county license issued before that date is no longer sufficient for new projects &mdash; this is a recent change that many Florida homeowners don&apos;t know yet.</p>
      <p>For states without a siding-specific classification, look for a &quot;general contractor,&quot; &quot;building contractor,&quot; or &quot;residential contractor&quot; license with a classification that includes exterior or building envelope work. The key question to ask: does this classification legally authorize siding installation in this state? State licensing board websites can confirm this, or you can check at <a href="https://checklicensed.com">CheckLicensed.com</a>. See also: <a href="/blog/contractor-license-types-explained">how contractor license classifications work</a> and <a href="/blog/what-is-residential-contractor-license">what a residential contractor license covers</a>.</p>

      <h2>Is a permit required for siding replacement?</h2>
      <p>Usually yes for full siding replacement, rarely for minor repairs. Most jurisdictions require a building permit for full re-siding projects because the work affects the building envelope and weatherproofing. Permits are separate from contractor licensing &mdash; a contractor can be licensed without pulling the required permit, which creates liability for the homeowner.</p>
      <p>Building permits are issued by local jurisdictions &mdash; city, county, or township &mdash; not state licensing boards. Full siding replacement almost always triggers a permit requirement because it involves the building envelope: removing and reinstalling the weatherproofing layer that protects your home&apos;s structure from moisture. Small repairs under a certain square footage threshold often do not require a permit, but the threshold varies by location.</p>
      <p>When a permit is pulled, an inspector will typically verify that flashing is correctly installed at windows, doors, and penetrations, that a moisture barrier or housewrap is in place, and that fastener patterns meet code. This inspection step is your warranty against water intrusion problems that might not appear for years.</p>
      <p>The permit is usually pulled in the contractor&apos;s name &mdash; not yours. But if your contractor does not pull the required permit and the work is later discovered to be unpermitted, you inherit that problem. Unpermitted work can complicate a home sale, trigger required remediation before closing, and void insurance claims for subsequent damage. If a contractor says &quot;we don&apos;t need a permit for a full re-side,&quot; that is a red flag worth investigating before work starts.</p>

      <h2>Why is siding a top target for contractor fraud?</h2>
      <p>Siding and roofing are consistently among the highest-complaint contractor categories nationally, especially after storms. Insurance payouts, high material costs, and the fact that most homeowners can&apos;t assess siding quality until years later make it ideal for fraudsters. Storm chasers specifically target neighborhoods after hail events, offering fast starts and taking deposits before disappearing.</p>
      <p>The storm-chaser model works because it exploits urgency. After a major hail or wind event, homeowners are motivated to act fast before more weather hits. Out-of-state crews follow storm paths, have no local license, no local accountability, and no intention of following up on warranty claims. They collect a deposit, do minimal or poor work, and move on before the problems surface.</p>
      <p>Insurance claim fraud adds another layer. Some contractors inflate estimates to exceed the actual damage, claiming hail damage on siding that was already worn or fine. Others pressure homeowners with a pitch that is illegal in most states: &quot;We&apos;ll waive your deductible.&quot; That offer &mdash; which sounds like a discount &mdash; is actually a form of insurance fraud in many states because the deductible is a contractual obligation between you and your insurer.</p>
      <p>The delayed-discovery problem is what makes siding fraud so damaging. Improper flashing, missing housewrap, or incorrectly fastened panels may not manifest as water infiltration, rot, or mold for two to five years. By then, the contractor is unreachable, their phone number is disconnected, and any deposit you paid is long gone. State attorney general consumer protection offices consistently rank siding and roofing among the highest-complaint contractor categories in the aftermath of major storms.</p>

      <h2>What manufacturer certifications should a siding contractor have?</h2>
      <p>Manufacturer certifications are not required by law but are a meaningful secondary verification. James Hardie (HardiePlank) offers a Preferred Contractor and Elite Preferred designation requiring training, insurance minimums, and installation testing. Mastic (Ply Gem) has a Certified Contractor program. These certifications exist independently of state licensing and indicate product-specific expertise and installation discipline.</p>
      <p>James Hardie, maker of fiber cement HardiePlank siding, runs two certification tiers. The Preferred Contractor designation requires proof of general liability and workers&apos; comp insurance, completion of installation training, and a minimum track record with the product. The Elite Preferred tier requires higher installation volume and additional vetting. Elite Preferred contractors can offer homeowners an extended 30-year warranty on the product &mdash; a meaningful benefit that Preferred Contractors cannot provide.</p>
      <p>Mastic and Ply Gem run their own Certified Contractor programs for vinyl siding. These certifications verify that the contractor has been trained on proper installation technique &mdash; fastener patterns, overlap requirements, expansion gaps &mdash; that directly affect long-term performance and warranty validity.</p>
      <p>Manufacturer certifications matter beyond marketing because installation errors void manufacturer warranties. The wrong fastener, incorrect overlap, or missing flashing at a window penetration is a warranty-voiding defect that you won&apos;t discover until you try to file a claim years later. You can verify manufacturer certifications through each brand&apos;s website contractor lookup tool by zip code. These certifications are an additional layer on top of state licensing, not a substitute for it.</p>

      <h2>How do I verify a siding contractor&apos;s license?</h2>
      <p>Go to your state&apos;s contractor licensing board website and search by the contractor&apos;s name or license number. Confirm the license is active, check that the classification covers siding or exterior work specifically, and review any complaint or disciplinary history. Do this before signing a contract or paying any deposit.</p>
      <p>Start by asking the contractor for their license number in writing. Any legitimate siding contractor will provide this without hesitation. If they say they&apos;ll get it to you later, or that the license is &quot;pending,&quot; or that they&apos;re licensed under their foreman&apos;s name &mdash; those are red flags that warrant stopping the conversation.</p>
      <p>With the license number in hand, go to the state licensing board. In California, that&apos;s the CSLB at cslb.ca.gov. In Florida, it&apos;s the DBPR at myfloridalicense.com. In Nevada, it&apos;s the NSCB at nscb.nv.gov. Confirm the status reads &quot;Active.&quot; Then verify the classification matches &mdash; for siding work, confirm the license type covers exterior or siding installation specifically, not just general construction.</p>
      <p>Check the disciplinary history while you&apos;re there. Prior complaints, citations for unlicensed work on job sites, or bond claims are patterns that matter. <a href="https://checklicensed.com">CheckLicensed.com</a> consolidates license status, classification, disciplinary history, BBB rating, and verified reviews in one search &mdash; faster than navigating each state board&apos;s site manually. Also check Google reviews for recent activity: a sudden flood of five-star reviews after a storm event, with no review history before it, is a sign of a chaser operation. See also: <a href="/blog/deck-contractor-license-requirements">deck contractor license requirements</a>, <a href="/blog/fence-contractor-license-requirements">fence contractor licensing</a>, and <a href="/blog/window-contractor-license-requirements">window installation contractor licenses</a> for the same verification process applied to other exterior trades. And before hiring anyone, review <a href="/blog/licensed-vs-bonded-vs-insured-contractors">what licensed, bonded, and insured actually means</a>.</p>

      <h2>What happens if a siding contractor is unlicensed?</h2>
      <p>Hiring an unlicensed siding contractor puts you at risk on multiple fronts: no recourse through the state licensing board if the work fails, likely no workers&apos; comp coverage if a worker is hurt at your home, and potential homeowners insurance complications if damage results from unlicensed work. In some states, unlicensed contractors cannot legally collect payment &mdash; but that doesn&apos;t help you recover a deposit already paid.</p>
      <p>Licensing board enforcement only applies to licensed contractors. If your siding contractor is unlicensed and the work fails &mdash; panels fall off, water gets behind the siding, flashing fails &mdash; you have no complaint mechanism through the state board. Your options shrink to civil litigation or small claims court, neither of which is fast or cheap.</p>
      <p>The workers&apos; comp exposure is significant. If an unlicensed siding contractor or their workers are injured at your property, the statutory employer doctrine may make you the legal employer responsible for that injury. This is not a hypothetical: siding installation involves ladders, scaffolding, and elevated work that results in real falls. See the full breakdown of <a href="/blog/homeowner-liability-unlicensed-contractor-injury">homeowner liability when a contractor is injured</a> on your property.</p>
      <p>Unlicensed work also creates insurance problems for the homeowner. If the siding installation causes or contributes to water damage &mdash; a slow leak from bad flashing that leads to rot and mold &mdash; your homeowners insurer may deny the damage claim on the grounds that the work was performed without a license. And if the contractor disappeared after taking a deposit, which is the storm-chaser standard play, recovering that money requires finding them, suing them, winning judgment, and actually collecting &mdash; a process that takes years and often produces nothing. Review the <a href="/blog/what-happens-hire-unlicensed-contractor">full consequences of hiring an unlicensed contractor</a> before making any hiring decision.</p>

      <p>Siding licensing is fragmented enough that &quot;licensed contractor&quot; is not a sufficient answer &mdash; you need to know the classification, confirm it covers exterior work, and verify the license is currently active. After any storm, run this check before anyone sets foot on a ladder. The five minutes it takes is the cheapest insurance available.</p>
    </>
  );
}
